name: github-actions-pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
         node-version: 16  
      - run: npm ci
      - run: npm test
      - run: npm run build
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          #cache-from: |
         #   type=gha,scope=base
         # cache-to: |
         #   type=gha,scope=base,mode=max
        #  target: base
          #tags: you/repo/backend:build-stage
